### ISSUE TITLE
Haxe 4.0.0-preview.3 errors

### ISSUE THREAD

**Issue by tong** [HaxeFoundation/record-macros#18]
- `record-macros/1,0,0-alpha/src/sys/db/RecordMacros.hx:736: characters 12-14 : Unmatched patterns: OpIn`

- `record-macros/1,0,0-alpha/src/sys/db/RecordMacros.hx:902: characters 8-11 : Identifier 'EIn' is not part of haxe.macro.ExprDef (Suggestion: EIf)`

- `record-macros/1,0,0-alpha/src/sys/db/RecordMacros.hx:902: characters 8-17 : Unrecognized pattern: EIn(e, v)`

**Comment by jonasmalacofilho** [comment]
*master* already has fixes for those errors (unless something else has changed).

@nadako: it would be nice if we could have a new haxelib release.  Is there anything I can do to help?
