### ISSUE TITLE
Bug in manager.search(true)

### ISSUE THREAD

**Issue by lyhil** [HaxeFoundation/record-macros#2]
Text.manager.search(true);

fails with:

    Uncaught exception - Error while executing SELECT * FROM Text WHERE TRUE (Sqlite error in SELECT * FROM Text WHERE TRUE : no such column: TRUE)

on Haxe 3.4.0 on neko target with latest haxelib version of record-macros.

**Comment by jonasmalacofilho** [comment]
This is related to HaxeFoundation/haxe#3044.

I'm developing a fix for it on https://github.com/jonasmalacofilho/record-macros/tree/fix-3044-support-postgres-without-breaking-sqlite ... it should already work for most use cases, but I would like to tackle the corner cases – essentially when there are multiple managers – before submitting.

**Comment by jonasmalacofilho** [comment]
SQLite added support for `TRUE`|`FALSE` constants last year, in [v3.23.0](https://www.sqlite.org/releaselog/3_23_0.html).

Unfortunately, that's still too recent and many installations will be running an older version.  For example, Ubuntu 18.04 LTS [still ships v3.22.0](https://packages.ubuntu.com/bionic/libsqlite3-0).
