### ISSUE TITLE
Problem with reference data going through Serializer/Unserializer

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/record-macros#54]
Hej !

I ran into a strange bug last days, I'm on it for 2-3 days trying to isolate it.
Let's say we have this : 
```haxe
class A
extends sys.db.Object
{
	var id : SId;

	@:relation( bID )
	public var b	: B;

	public function new(){
		super();
	}
}

class B
extends sys.db.Object
{
	var id : SId;

	@:relation( aID )
	public var a	: A;
	
	public function new(){
		super();
	}
}
```

```haxe
class Main{
    static function main(){
        var a	= new A();
	var b	= new B();
	a.b	= b;
	b.a	= a;
		
	trace( a == a.b.a );                                            // <--------------------------- true

	var ser		= Serializer.run( a );
	var a2	: A     = Unserializer.run( ser );

	trace( a2 == a2.b.a );                                          // <--------------------------- true
    }
}
```

```haxe
class Main{
    static function main(){
       var a	= A.manager.get( 1 );
		
	trace( a == a.b.a );                                             // <--------------------------- true

	var ser		= Serializer.run( a );
	var a2	: A     = Unserializer.run( ser );

	trace( a2 == a2.b.a );                                           // <--------------------------- false !!!
    }
}
```
My bug isn't that but when digging, I noticed this strange behaviour and I think my bug could come from that.
My real bug comes from `lock` arg in `.unsafeObject()`, when set to false something is going wrong and all works fine when it's true. Maybe it can help you... or maybe it will mess. Anyway, the pasted code here is my question here.

**Comment by jonasmalacofilho** [comment]
I'm not sure I'm completely understand you, but

```haxe
var a2	: A     = Unserializer.run( ser );
```

will create `a2`  "from thin air", bypassing the record-macros cache and, thus, resulting in a different class instance than the one the manager fetches when you do `a2.b.a`.   Additionally, even in the first example I imagine that `a2 == b.a` would also fail.

I think you simply can't expect this much from `Serializer`, or any serialization library.  By its very nature, unless there is tight cooperation between all involved libraries, serialization can't preserve (or, rather, recreate) such identifies.

You could perhaps compare by value, a.k.a. do a deep comparison.  But even then, beware of the fact that the record-macros manager expects to know about all in-use object/record instances; its cache is more akin to a coherence engine (side note: carelessly clearing the cache can result in unexpected behavior).

Alternatively, you can send serializer-safe references to the objects, like their IDs.  This should be a lot safer, as long as both sender and receiver are aware that the database may change between these calls.  And you may also need to consider things transactions: if the receiver has opened its database transaction before the object was created by the sender, it wont see it.

**Comment by jonasmalacofilho** [comment]
_(Meant to include the following at the end of the previous comment...)_

> My real bug comes from lock arg in .unsafeObject(), when set to false something is going wrong and all works fine when it's true.

This is what I didn't understand.  What exactly is the bug, and what is this wrong behavior?  How does this relate to serialization of references problem?

**Comment by filt3rek** [comment]
Thanks Jonas for your answer.

When you write "will create a2 "from thin air", bypassing the record-macros cache" I understand that the first trace should also give me "false", but it gives true.
INHO the problem comes from when it goes through Serializer.

**Comment by filt3rek** [comment]
And my real bug occurs when I get objects with `unsafeObjects()`with `lock` set to `false`, then when I iterate over my objects then I change a field on them, the changes are taken in account but is I pass these objects through Serializer, the changes are lost.
If `lock` is set to `true`, passing objects through Serializer keep these changes...
That's why then when I looked at the references that are not the same I thought that something is linked to that loose of reference.

**Comment by jonasmalacofilho** [comment]
> When you write "will create a2 "from thin air", bypassing the record-macros cache" I understand that the first trace should also give me "false", but it gives true.

Yes, things could be a bit more complex.  You only showed a partial example, and without seeing the state of the manager (and actually running the code), I'm just guessing.

But my point is that, indeed, the issue is (probably?) trying to serialize/unserialize those references.

---

> That's why then when I looked at the references that are not the same I thought that something is linked to that loose of reference.

Again, without seeing a minimal reproduceable example, I'm only able to throw some guesses.

But by sending the objects through the serializer you may end up with duplicated instances (or, at least, instances the manager doesn't know about).  The whole locking mechanism of record-macros heavily depends on the "cache" and if there are instances it doesn't know about, you'll get unexpected behavior.

It also isn't clear whether these objects are directly changed and sent through the serializer, or not.  This could matter: any non-physical field (on the particular target you're running) may not be survive the serialization like you expect.

**Comment by filt3rek** [comment]
Jonas,

I tried to give you a minimal example to "reproduce" the problem.
Nothing is done elsewhere, manager is not touched.
The only thing is that the `Serializer.USE_CACHE = true` to avoid infinite loop for circular references (as here).
And the output platefor is PHP.
If you could just create these 2 tables and test this minimal code, you'll se.
Or tell me please what to do more but as I wrote, I tried to do an example as minimal as possible to reproduce the problem.

**Comment by filt3rek** [comment]
Here is the "main code" : 
```haxe
class Main{
     sys.db.Manager.cnx	= sys.db.Mysql.connect( { host	: "localhost", user :"roo", pass : "", database : "MyDB" } );
    sys.db.Manager.cnx.request( "SET NAMES utf8" );
     sys.db.Manager.initialize();
     sys.db.Manager.cleanup();
    
      var a	= A.manager.get( 1 );
		
	trace( a == a.b.a );                                             // <--------------------------- true

	var ser		= Serializer.run( a );
	var a2	: A     = Unserializer.run( ser );

	trace( a2 == a2.b.a );                                           // <--------------------------- false !!!
}
```

**Comment by filt3rek** [comment]
I wouldn't "insist" like that if all give me true/true or false/false, but here we've got true/false for the second example and that is strange.

**Comment by filt3rek** [comment]
And here the sql tables : 
```sql
CREATE TABLE IF NOT EXISTS `A` (
`id` int(11) NOT NULL,
  `bID` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `A` (`id`, `bID`) VALUES
(1, 1);

CREATE TABLE IF NOT EXISTS `B` (
`id` int(11) NOT NULL,
  `aID` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `B` (`id`, `aID`) VALUES
(1, 1);
```

**Comment by jonasmalacofilho** [comment]
I appreciate the effort.  Here's the code with annotations explaining what's going on:

```haxe
import sys.db.Types;

class A extends sys.db.Object {
	var id:SId;

	@:relation(bID)
	public var b:B;
}

class B extends sys.db.Object {
	var id:SId;

	@:relation(aID)
	public var a:A;
}

class Main {
	static function dumpCacheKeys() {
		return [for (key in @:privateAccess sys.db.Manager.object_cache) key];
	}

	static function main() {
		haxe.Serializer.USE_CACHE = true;
		sys.db.Manager.cnx = sys.db.Sqlite.open(":memory:");
		sys.db.Manager.cnx.request("CREATE TABLE A AS SELECT 1 id, 1 bID");
		sys.db.Manager.cnx.request("CREATE TABLE B AS SELECT 1 id, 1 aID");

		var a = A.manager.get(1);                    // caches a
		trace('cached keys: ${dumpCacheKeys()}');    // cached keys: [A#1]

		trace('assertion on `a`: ${a == a.b.a}');    // caches b, reuses a
		trace('cached keys: ${dumpCacheKeys()}');    // cached keys: [A#1,B#1]

		var ser = haxe.Serializer.run(a);
		var a2:A = haxe.Unserializer.run(ser);

		trace('assertion on `a2`: ${a2 == a2.b.a}');  // reuses b, reuses a (not a2), thus a2 != a
		trace('cached keys: ${dumpCacheKeys()}');     // cached keys: [A#1,B#1]
	}
}
```

```
$ haxe --library record-macros --main Main --php target/php
php target/php/index.php
Main.hx:37: cached keys: [A#1]
Main.hx:39: assertion on `a`: true
Main.hx:40: cached keys: [A#1,B#1]
Main.hx:45: assertion on `a2`: false
Main.hx:46: cached keys: [A#1,B#1]

$ haxe --version
4.2.0-rc.1+c9408747b451  # current HEAD

$ (cd .haxelib/record-macros/git && git --no-pager log -1 --format=%h --abbrev=12)
1b8f6adcc46b  # current HEAD
```

P.S. Note how using SQLite in examples that don't depend on a particular engine leads to a much cleaner, self-contained, and easier to run test case.  I'm also using an in-memory database, which ensures that every new connection starts with a fresh new database.

**Comment by filt3rek** [comment]
Thanks Jonas for all your explaination and the advices !
Hmm my brain is a bit like jam now but ok.
But why in the first example, with "new" objects, when going through Serializer, "reuses b, reuses a (not a2), thus a2 != a" it "reuses" a2 ? Do you know what I mean ?

**Comment by jonasmalacofilho** [comment]
That's a good question, and I think I found a bug.  But first, this is what happens in the first case:

```haxe
// these physically set a.b and b.a 
var a = new A();
var b = new B();
a.b = b;
b.a = a;
trace('physical a.b: ${Reflect.field(a, "b") != null}'); // true
trace('physical b.a: ${Reflect.field(b, "a") != null}'); // true

// since a.b was physically set, b is serialized too
var ser = haxe.Serializer.run(a);
var a2:A = haxe.Unserializer.run(ser);
trace("after [un]serialization...");
trace('physical a2.b: ${Reflect.field(a2, "b") != null}'); // true

// but, and this is very important, all of the following are false
trace('a2 == a: ${a2 == a}'); // false, new instance created by the serializer
trace('a2.b == b: ${a2.b == b}'); // false, new instance created by the serializer
trace('a2.b.a == a: ${a2.b.a == a}'); // false, new (cached a2) instance created by the serializer

// still
trace('a2 == a2.b.a: ${a2 == a2.b.a}'); // true, a2.b.a reuses a2

// by the way
trace('cached keys: ${dumpCacheKeys()}'); // empty, there has been no db access at all
```

Which brings me to the difference with the second case...

The manager doesn't physically store the object in the corresponding field (i.e. doesn't set a `B` instance in `a.b`) when accessing `a.b` for the first time.  Thus, in the second case, the serializer sees a `null`, `a.b` is left to be resolved after the unserialization, that results in accessing the cache, and it only has the first `a` but not the second `a2`.

And the probable bug is that the corresponding manager code looks like it was meant to store the object in `a.b`, but...

https://github.com/HaxeFoundation/record-macros/blob/1b8f6adcc46b7698d1d5060283a590afe81b257d/src/sys/db/Manager.hx#L629-L636

note the use of visual similar but different `v` and `y` variables.  I'll change this and see if the tests complain.

---

That said, you still should consider _not_ serializing `sys.db.Object`s, or, at least, not using any features from record-macros on these objects after they have been through a serialization/deserialization roundtrip.

Even if my fix is successful, `a2` will be a different instance than `a`.  This breaks all coherence guarantees that record-macros usually (more or less) provides.

Additionally, whether or not `a2 == a2.b.a` will be true will depend on whether `a.b` and `b.a` had been fetched and stored physically before the serialization; in the second case we're discussing, this only happens because of a trace (`a == a.b.a`).

**Comment by filt3rek** [comment]
Hej Jonas,
Fisrt, many thanks for your investigation, I know it's not an easy task with something "heavy" like the manager and all these little things that are done everywhere. Also working with cycling references is not easy neither, it's really a brain f**k :smile: 

Also I want to tell you that of course, I don't serialize db objects for my pleasure or to store them as it and then use it. I use Serializer through remoting to send objects to the client, but here for the minimal example I've use it on the server side like that.

And all I want to do is just to access the object's fields on the client side. Here comes my initial bug that I will try to isolate and make aagain a minimal example in another thread.

So I'm sorry for that first thread that was not the initial bug and put us on a bad path. The only good thing in that is that it had helped to find another bug :)

See you later on another thread, have a nice day !

**Comment by filt3rek** [comment]
Another thing is that I've tried your fix, and as said it doesn't solve my initial bug BUT now the 2 assertions are "true", so yes, It was really a bug, thanks ! :)
