### ISSUE TITLE
Foreign key or setter bug since haxe 3.4.2

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/record-macros#6]
I installed yesterday haxe 3.4.2 after using 3.2.1 for a long time ( yes ... I know )
Therefore I installed the record-macros lib.

Allmost all the INSERT operations in my app are broken when they involve relations / foreign key.

In the example code below, the Transaction records should be stored with a userId and groupId.
The bug is that groupId is 0 , instead of the correct group id.
My guess is that when I set a relation from another relation (i.e : t.group = u.group;   ) the setter doesn't work, since it was working perfectly in haxe 3.2.1

In my real-life-application, which has foreign key constraints ( managed by dbadmin lib ) and gives me MySQL errors like this "INSERT INTO Contract (name,startDate,endDate,distributorNum,flags,type,userId,vendorId) VALUES ('Commande Aromatiques', '2017-03-22 13:24:23', '2018-03-22 00:00:00', 0, 0, 1, 6459, 849) Cannot add or update a child row: a foreign key constraint fails (`cagette`.`Contract`, CONSTRAINT `Contract_amap` FOREIGN KEY (`amapId`) REFERENCES `Amap` (`id`) ON DELETE CASCADE)"

`
package;
import sys.db.Types;

class SpodBug
{

	public static function main(){
		
		var cnx = sys.db.Mysql.connect({
		   host : "localhost",
		   port : null,
		   user : "cagette",
		   pass : "cagette",
		   database : "test",
		   socket : null,
		});
		
		sys.db.Manager.cnx = cnx;
		
		sys.db.Manager.initialize();
		
		trace("cnx : "+cnx);
		
		create(User.manager);
		create(Group.manager);
		create(Transaction.manager);
		
		var g = new Group();
		g.name = "the winnerz";
		g.insert();
		
		var u = new User();
		u.name = "Bob";
		u.group = g;
		u.insert();
		
		var t = new Transaction();
		t.user = u;
		t.group = u.group; // THIS WONT WORK
		t.insert();
		
		trace(t.toString());
		
	}
	
	static function create( m  ){
		if ( !sys.db.TableCreate.exists(m) ){
			trace("creating table "+ m.dbInfos().name);
			sys.db.TableCreate.create(m);
		}
	}
	
}

class User extends sys.db.Object {
    public var id : SId;
	public var name : SString<32>;
	@:relation(groupId) public var group  : Group;
    
}
class Group extends sys.db.Object {
   public var id : SId;
   public var name : SString<32>;
   
}

class Transaction extends sys.db.Object {
	public var id : SId;
	
    @:relation(userId) 	public var user : User;
    @:relation(groupId) public var group : Group;
	
	override public function toString(){
		return "transaction " + id + " of " + user +" from " + group;
	}
}
`

**Comment by bablukid** [comment]
Found a workaround : doing it in two steps fixes the problem.
The code is run on neko 2.1.0

```
var t = new Transaction();
		t.user = u;
		var group = u.group;
		t.group = group; //THIS WORK
		t.insert();
```

**Comment by jonasmalacofilho** [comment]
Seems the same as HaxeFoundation/haxe#6048

**Comment by jonasmalacofilho** [comment]
@bablukid , check out #9 ... it should fix it

**Comment by bablukid** [comment]
Wow, it looks the problem is solved ... thank you so much !
